# Generated by Django 5.2.6 on 2025-09-28 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veteran_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veteran_app.state')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
