# Generated by Django 4.2.7 on 2025-10-15 06:04

import django.core.validators
from django.db import migrations, models
import veteran_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('veteran_app', '0002_userstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veteranmember',
            name='document',
            field=models.FileField(blank=True, help_text='Allowed formats: PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, JPG, JPEG, PNG, GIF, BMP, TIFF, SVG, TXT, RTF, ODT, ODS, ODP, ZIP, RAR', null=True, upload_to=veteran_app.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'jpg', 'jpeg', 'png', 'gif', 'bmp', 'tiff', 'svg', 'txt', 'rtf', 'odt', 'ods', 'odp', 'zip', 'rar'])]),
        ),
    ]
