# Generated by Django 4.2.7 on 2025-10-15 06:33

import django.core.validators
from django.db import migrations, models
import veteran_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('veteran_app', '0003_alter_veteranmember_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='carousel/')),
                ('icon_class', models.CharField(default='fas fa-info-circle', help_text='FontAwesome icon class', max_length=50)),
                ('background_color', models.CharField(default='bg-gradient-primary', max_length=50)),
                ('order', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='veteranmember',
            name='document',
            field=models.FileField(blank=True, help_text='Attach any document: PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, JPG, JPEG, PNG, GIF, BMP, TIFF, SVG, TXT, RTF, ODT, ODS, ODP, ZIP, RAR', null=True, upload_to=veteran_app.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'jpg', 'jpeg', 'png', 'gif', 'bmp', 'tiff', 'svg', 'txt', 'rtf', 'odt', 'ods', 'odp', 'zip', 'rar'])]),
        ),
    ]
