# Generated by Django 4.2.7 on 2025-10-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veteran_app', '0004_carouselslide_alter_veteranmember_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstate',
            options={'verbose_name': 'User State Assignment', 'verbose_name_plural': 'User State Assignments'},
        ),
        migrations.AddField(
            model_name='userstate',
            name='approved',
            field=models.BooleanField(default=False, help_text='Approved by superadmin to access the system'),
        ),
        migrations.AddField(
            model_name='userstate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userstate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
