# Generated by Django 4.2.7 on 2025-10-15 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veteran_app', '0005_alter_userstate_options_userstate_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('success', 'Success'), ('urgent', 'Urgent')], default='info', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Notification expiry date', null=True)),
                ('state', models.ForeignKey(blank=True, help_text='Leave blank for all states', null=True, on_delete=django.db.models.deletion.CASCADE, to='veteran_app.state')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Document title', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Brief description of the document')),
                ('document_type', models.CharField(choices=[('circular', 'Circular'), ('notification', 'Notification'), ('form', 'Form'), ('guideline', 'Guideline'), ('policy', 'Policy Document'), ('announcement', 'Announcement'), ('other', 'Other')], default='notification', max_length=50)),
                ('file', models.FileField(help_text='Upload PDF, DOC, or image files', upload_to='documents/%Y/%m/')),
                ('is_public', models.BooleanField(default=True, help_text='Visible to all users')),
                ('is_important', models.BooleanField(default=False, help_text='Mark as important/urgent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.ForeignKey(blank=True, help_text='Leave blank for all states, or select specific state', null=True, on_delete=django.db.models.deletion.CASCADE, to='veteran_app.state')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents & Media',
                'ordering': ['-is_important', '-created_at'],
            },
        ),
    ]
