# Generated by Django 4.2.7 on 2025-10-15 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veteran_app', '0006_notification_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='VeteranUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False, help_text='Approved by state admin')),
                ('created_by_admin', models.BooleanField(default=False, help_text='Created by state admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='veteran_profile', to=settings.AUTH_USER_MODEL)),
                ('veteran_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='veteran_app.veteranmember')),
            ],
            options={
                'verbose_name': 'Veteran User Account',
                'verbose_name_plural': 'Veteran User Accounts',
            },
        ),
    ]
