# Generated by Django 4.2.7 on 2025-10-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veteran_app', '0007_veteranuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='veteranmember',
            name='alternate_email',
            field=models.EmailField(blank=True, help_text='Secondary email address', max_length=254),
        ),
        migrations.AddField(
            model_name='veteranmember',
            name='bank_account',
            field=models.CharField(blank=True, help_text='Bank account number', max_length=100),
        ),
        migrations.AddField(
            model_name='veteranmember',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name and branch', max_length=200),
        ),
        migrations.AddField(
            model_name='veteranmember',
            name='children_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of children'),
        ),
        migrations.AddField(
            model_name='veteranmember',
            name='decorations',
            field=models.TextField(blank=True, help_text='Awards, medals, and decorations received'),
        ),
        migrations.AddField(
            model_name='veteranmember',
            name='deployment_history',
            field=models.TextField(blank=True, help_text='Brief deployment history'),
        ),
        migrations.AddField(
            model_name='veteranmember',
            name='disabilities',
            field=models.TextField(blank=True, help_text='Service-related disabilities'),
        ),
        migrations.AddField(
            model_name='veteranmember',
            name='emergency_contact_name',
            field=models.CharField(blank=True, help_text='Emergency contact person', max_length=200),
        ),
        migrations.AddField(
            model_name='veteranmember',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, help_text='Emergency contact number', max_length=15),
        ),
        migrations.AddField(
            model_name='veteranmember',
            name='insurance_details',
            field=models.TextField(blank=True, help_text='Medical insurance information'),
        ),
        migrations.AddField(
            model_name='veteranmember',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='Known medical conditions'),
        ),
        migrations.AddField(
            model_name='veteranmember',
            name='next_of_kin',
            field=models.CharField(blank=True, help_text='Next of kin/legal heir', max_length=200),
        ),
        migrations.AddField(
            model_name='veteranmember',
            name='next_of_kin_contact',
            field=models.CharField(blank=True, help_text='Next of kin contact number', max_length=15),
        ),
        migrations.AddField(
            model_name='veteranmember',
            name='next_of_kin_relation',
            field=models.CharField(blank=True, help_text='Relationship with next of kin', max_length=50),
        ),
        migrations.AddField(
            model_name='veteranmember',
            name='pension_details',
            field=models.TextField(blank=True, help_text='Pension scheme details'),
        ),
        migrations.AddField(
            model_name='veteranmember',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Upload profile photo (JPG, PNG)', null=True, upload_to='profiles/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='veteranmember',
            name='service_number',
            field=models.CharField(blank=True, help_text='Military service number', max_length=50),
        ),
        migrations.AddField(
            model_name='veteranmember',
            name='specialization',
            field=models.CharField(blank=True, help_text='Area of expertise/specialization', max_length=200),
        ),
        migrations.AddField(
            model_name='veteranmember',
            name='spouse_name',
            field=models.CharField(blank=True, help_text='Spouse full name', max_length=200),
        ),
        migrations.AddField(
            model_name='veteranmember',
            name='unit_served',
            field=models.CharField(blank=True, help_text='Last unit/ship served', max_length=200),
        ),
        migrations.AddField(
            model_name='veteranmember',
            name='welfare_schemes',
            field=models.TextField(blank=True, help_text='Enrolled welfare programs'),
        ),
    ]
