# Generated by Django 4.2.7 on 2025-10-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veteran_app', '0008_veteranmember_alternate_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veteranmember',
            name='nearest_dhq',
            field=models.CharField(blank=True, help_text='Nearest District Headquarters for service support', max_length=200),
        ),
    ]
