# Generated by Django 4.2.7 on 2025-10-17 16:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import veteran_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('veteran_app', '0009_veteranmember_nearest_dhq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_photo', models.ImageField(blank=True, help_text='Child photo', null=True, upload_to='children/%Y/%m/')),
                ('child_name', models.CharField(max_length=200)),
                ('child_dob', models.DateField(verbose_name='Date of Birth')),
                ('child_qualification', models.CharField(blank=True, help_text='Educational qualification', max_length=200)),
                ('specialization', models.CharField(blank=True, help_text='Area of specialization if any', max_length=200)),
                ('searching_for_job', models.BooleanField(default=False, help_text='Looking for job opportunities')),
                ('searching_for_alliance', models.BooleanField(default=False, help_text='Looking for matrimonial alliance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Child',
                'verbose_name_plural': 'Children',
                'ordering': ['child_dob'],
            },
        ),
        migrations.CreateModel(
            name='MedicalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., S1A1, S2A2, S3A3', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of medical category')),
            ],
            options={
                'verbose_name': 'Medical Category',
                'verbose_name_plural': 'Medical Categories',
            },
        ),
        migrations.RemoveField(
            model_name='veteranmember',
            name='nearest_dhq',
        ),
        migrations.AddField(
            model_name='veteranmember',
            name='educational_qualification',
            field=models.CharField(blank=True, help_text='Highest educational qualification', max_length=200),
        ),
        migrations.AddField(
            model_name='veteranmember',
            name='living_city',
            field=models.CharField(blank=True, help_text='Current city of residence', max_length=100),
        ),
        migrations.AddField(
            model_name='veteranmember',
            name='nearest_dhq_text',
            field=models.CharField(blank=True, help_text='Nearest District Headquarters (text)', max_length=200),
        ),
        migrations.AddField(
            model_name='veteranmember',
            name='nearest_veteran_contact',
            field=models.CharField(blank=True, help_text='Nearest veteran contact number', max_length=15),
        ),
        migrations.AddField(
            model_name='veteranmember',
            name='searching_for_job',
            field=models.BooleanField(default=False, help_text='Looking for job opportunities'),
        ),
        migrations.AddField(
            model_name='veteranmember',
            name='spouse_contact',
            field=models.CharField(blank=True, help_text='Spouse contact number', max_length=15),
        ),
        migrations.AddField(
            model_name='veteranmember',
            name='spouse_employed',
            field=models.CharField(blank=True, help_text='Spouse employment details', max_length=200),
        ),
        migrations.AddField(
            model_name='veteranmember',
            name='spouse_medical_details',
            field=models.TextField(blank=True, help_text='Spouse medical information'),
        ),
        migrations.AddField(
            model_name='veteranmember',
            name='subscription_due',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='veteranmember',
            name='decorations',
            field=models.TextField(blank=True, help_text='Awards, medals, and decorations received', verbose_name='Awards & Decorations'),
        ),
        migrations.AlterField(
            model_name='veteranmember',
            name='document',
            field=models.FileField(blank=True, help_text='Subscription payment document or support document', null=True, upload_to=veteran_app.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'jpg', 'jpeg', 'png', 'gif', 'bmp', 'tiff', 'svg', 'txt', 'rtf', 'odt', 'ods', 'odp', 'zip', 'rar'])]),
        ),
        migrations.AlterField(
            model_name='veteranmember',
            name='membership',
            field=models.BooleanField(default=False, verbose_name='Active Membership'),
        ),
        migrations.AlterField(
            model_name='veteranmember',
            name='p_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Service Number'),
        ),
        migrations.AlterField(
            model_name='veteranmember',
            name='retired_on',
            field=models.DateField(verbose_name='Date of Retirement'),
        ),
        migrations.AlterField(
            model_name='veteranmember',
            name='unit_served',
            field=models.CharField(blank=True, help_text='Last unit/ship served', max_length=200, verbose_name='Last Ship Served'),
        ),
        migrations.CreateModel(
            name='Matrimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, help_text='Profile photo', null=True, upload_to='matrimonial/%Y/%m/')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('height', models.CharField(blank=True, help_text='Height in cm or feet', max_length=20)),
                ('religion', models.CharField(blank=True, max_length=100)),
                ('caste', models.CharField(blank=True, max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('annual_income', models.CharField(blank=True, max_length=100)),
                ('about', models.TextField(blank=True, help_text='Brief description')),
                ('expectations', models.TextField(blank=True, help_text='Partner expectations')),
                ('contact_person', models.CharField(blank=True, help_text='Contact person name', max_length=200)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('is_active', models.BooleanField(default=True, help_text='Active profile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matrimonial_profile', to='veteran_app.child')),
                ('veteran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrimonial_profiles', to='veteran_app.veteranmember')),
            ],
            options={
                'verbose_name': 'Matrimonial Profile',
                'verbose_name_plural': 'Matrimonial Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_type', models.CharField(choices=[('veteran', 'Veteran'), ('child', 'Veteran Child')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('qualification', models.CharField(max_length=200)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('experience', models.TextField(blank=True, help_text='Work experience details')),
                ('skills', models.TextField(blank=True, help_text='Key skills')),
                ('preferred_location', models.CharField(blank=True, max_length=200)),
                ('resume', models.FileField(blank=True, help_text='Upload resume (PDF, DOC, DOCX)', null=True, upload_to='resumes/%Y/%m/')),
                ('is_active', models.BooleanField(default=True, help_text='Active job seeker')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='veteran_app.child')),
                ('veteran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='veteran_app.veteranmember')),
            ],
            options={
                'verbose_name': 'Job Portal Entry',
                'verbose_name_plural': 'Job Portal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ECHS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='veteran_app.state')),
            ],
            options={
                'verbose_name': 'ECHS Center',
                'verbose_name_plural': 'ECHS Centers',
            },
        ),
        migrations.CreateModel(
            name='DHQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='veteran_app.state')),
            ],
            options={
                'verbose_name': 'District Headquarters',
                'verbose_name_plural': 'District Headquarters',
            },
        ),
        migrations.AddField(
            model_name='child',
            name='veteran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='veteran_app.veteranmember'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='veteran_app.veteranmember')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='veteran_app.veteranmember')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='veteranmember',
            name='medical_category',
            field=models.ForeignKey(blank=True, default=None, help_text='Medical category (default: S1A1)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='veteran_app.medicalcategory'),
        ),
        migrations.AddField(
            model_name='veteranmember',
            name='nearest_echs',
            field=models.ForeignKey(blank=True, help_text='Nearest ECHS center', null=True, on_delete=django.db.models.deletion.SET_NULL, to='veteran_app.echs'),
        ),
        migrations.CreateModel(
            name='ChatRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Initial message or reason for contact')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_requests_received', to='veteran_app.veteranmember')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_requests_sent', to='veteran_app.veteranmember')),
            ],
            options={
                'verbose_name': 'Chat Request',
                'verbose_name_plural': 'Chat Requests',
                'ordering': ['-created_at'],
                'unique_together': {('requester', 'recipient')},
            },
        ),
    ]
