# Generated by Django 4.2.7 on 2025-10-17 16:37

from django.db import migrations, models


def set_default_values(apps, schema_editor):
    """Set default values for existing records"""
    VeteranMember = apps.get_model('veteran_app', 'VeteranMember')
    for veteran in VeteranMember.objects.all():
        if not veteran.service_number:
            veteran.service_number = veteran.p_number or 'N/A'
        if not veteran.unit_served:
            veteran.unit_served = 'Not Specified'
        if not veteran.nearest_dhq_text:
            veteran.nearest_dhq_text = 'Not Specified'
        if not veteran.spouse_name:
            veteran.spouse_name = 'Not Specified'
        veteran.save()


class Migration(migrations.Migration):

    dependencies = [
        ('veteran_app', '0010_child_medicalcategory_and_more'),
    ]

    operations = [
        # First, run data migration to set defaults
        migrations.RunPython(set_default_values, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='veteranmember',
            name='date_of_joining',
            field=models.DateField(verbose_name='Date of Joining'),
        ),
        migrations.AlterField(
            model_name='veteranmember',
            name='decorations',
            field=models.TextField(blank=True, help_text='Awards, medals, and decorations received', null=True, verbose_name='Awards & Decorations'),
        ),
        migrations.AlterField(
            model_name='veteranmember',
            name='deployment_history',
            field=models.TextField(blank=True, help_text='Brief deployment history', null=True),
        ),
        migrations.AlterField(
            model_name='veteranmember',
            name='nearest_dhq_text',
            field=models.CharField(help_text='Nearest District Headquarters', max_length=200, verbose_name='Nearest DHQ'),
        ),
        migrations.AlterField(
            model_name='veteranmember',
            name='service_number',
            field=models.CharField(help_text='Military service number', max_length=50, verbose_name='Service Number'),
        ),
        migrations.AlterField(
            model_name='veteranmember',
            name='specialization',
            field=models.TextField(blank=True, help_text='Area of expertise/specialization', null=True),
        ),
        migrations.AlterField(
            model_name='veteranmember',
            name='spouse_contact',
            field=models.CharField(blank=True, help_text='Spouse contact number', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='veteranmember',
            name='spouse_employed',
            field=models.CharField(blank=True, help_text='Spouse employment details', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='veteranmember',
            name='spouse_medical_details',
            field=models.TextField(blank=True, help_text='Spouse medical information', null=True),
        ),
        migrations.AlterField(
            model_name='veteranmember',
            name='spouse_name',
            field=models.CharField(help_text='Spouse full name', max_length=200),
        ),
        migrations.AlterField(
            model_name='veteranmember',
            name='unit_served',
            field=models.CharField(help_text='Last unit/ship served', max_length=200, verbose_name='Last Ship Served'),
        ),
    ]
