# Generated by Django 4.2.9 on 2025-11-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veteran_app', '0012_bankaccount_expensecategory_financialyear_and_more'),
    ]

    operations = [
        # First, update any empty p_numbers to a unique value to avoid constraint issues
        migrations.RunSQL(
            "UPDATE veteran_app_veteranmember SET p_number = 'LEGACY_' || association_id WHERE p_number = '';",
            reverse_sql="UPDATE veteran_app_veteranmember SET p_number = '' WHERE p_number LIKE 'LEGACY_%';"
        ),
        # Then alter the field to allow NULL values
        migrations.AlterField(
            model_name='veteranmember',
            name='p_number',
            field=models.CharField(blank=True, help_text='Legacy P-Number (optional)', max_length=50, null=True, verbose_name='P Number'),
        ),
        # Finally, convert any legacy entries to NULL for cleaner data
        migrations.RunSQL(
            "UPDATE veteran_app_veteranmember SET p_number = NULL WHERE p_number LIKE 'LEGACY_%';",
            reverse_sql="UPDATE veteran_app_veteranmember SET p_number = 'LEGACY_' || association_id WHERE p_number IS NULL;"
        ),
    ]
