# Generated by Django 4.2.9 on 2025-11-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veteran_app', '0013_auto_20251105_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='veteranmember',
            name='medical_category_text',
            field=models.CharField(blank=True, help_text='Enter custom medical category if not in dropdown', max_length=100, null=True, verbose_name='Medical Category (Custom)'),
        ),
        migrations.AddField(
            model_name='veteranmember',
            name='nearest_echs_text',
            field=models.CharField(blank=True, help_text='Enter custom ECHS center if not in dropdown', max_length=200, null=True, verbose_name='Nearest ECHS (Custom)'),
        ),
        migrations.AlterField(
            model_name='veteranmember',
            name='p_number',
            field=models.CharField(blank=True, help_text='Association Number (optional)', max_length=50, null=True, verbose_name='Assn. Number'),
        ),
        migrations.AlterField(
            model_name='veteranmember',
            name='service_number',
            field=models.CharField(help_text='Military service number (unique)', max_length=50, unique=True, verbose_name='Service Number'),
        ),
    ]
