# Generated by Django 4.2.9 on 2025-11-09 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veteran_app', '0014_veteranmember_medical_category_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrimonial',
            name='child_name',
            field=models.CharField(blank=True, help_text='Enter child name if not in dropdown', max_length=200, null=True, verbose_name='Child Name'),
        ),
        migrations.AlterField(
            model_name='matrimonial',
            name='child',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matrimonial_profile', to='veteran_app.child'),
        ),
    ]
