# Generated by Django 4.2.9 on 2025-11-20 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veteran_app', '0018_alter_branch_options_alter_veteranmember_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('veteran', 'Veteran Report'), ('financial', 'Financial Report'), ('administrative', 'Administrative Report')], max_length=50)),
                ('selected_columns', models.JSONField(help_text='List of selected column names')),
                ('filters', models.JSONField(default=dict, help_text='Applied filters')),
                ('is_template', models.BooleanField(default=False, help_text='System template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
