# Generated by Django 4.2.9 on 2025-11-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veteran_app', '0020_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='veteranmember',
            name='zip_code',
            field=models.CharField(blank=True, help_text='Postal/ZIP code', max_length=10),
        ),
    ]
