# Generated by Django 4.2.9 on 2025-11-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veteran_app', '0021_veteranmember_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstate',
            name='bio',
            field=models.TextField(blank=True, help_text='Brief bio or message'),
        ),
        migrations.AddField(
            model_name='userstate',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Contact number', max_length=15),
        ),
        migrations.AddField(
            model_name='userstate',
            name='designation',
            field=models.CharField(blank=True, help_text='e.g., State President, State Secretary', max_length=100),
        ),
        migrations.AddField(
            model_name='userstate',
            name='email',
            field=models.EmailField(blank=True, help_text='Official email', max_length=254),
        ),
        migrations.AddField(
            model_name='userstate',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full name of state head', max_length=200),
        ),
        migrations.AddField(
            model_name='userstate',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='State head profile photo', null=True, upload_to='state_heads/%Y/'),
        ),
    ]
