# Generated by Django 4.2.9 on 2025-11-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veteran_app', '0022_userstate_bio_userstate_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veteranmember',
            name='subscription_ref_no',
            field=models.CharField(blank=True, help_text='Subscription reference number (mandatory for new registrations)', max_length=100, null=True, verbose_name='Subscription Ref.No'),
        ),
    ]
