# Generated by Django 4.2.9 on 2025-11-24 16:08

from django.db import migrations, models
import veteran_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('veteran_app', '0023_add_subscription_ref_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contact_phone',
            field=models.CharField(max_length=15, validators=[veteran_app.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='jobportal',
            name='contact',
            field=models.CharField(max_length=15, validators=[veteran_app.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='matrimonial',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, validators=[veteran_app.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='userstate',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Contact number', max_length=15, validators=[veteran_app.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='veteranmember',
            name='contact',
            field=models.CharField(help_text='10-digit mobile number', max_length=15, validators=[veteran_app.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='veteranmember',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, help_text='Emergency contact number', max_length=15, validators=[veteran_app.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='veteranmember',
            name='nearest_veteran_contact',
            field=models.CharField(blank=True, help_text='Nearest veteran contact number', max_length=15, validators=[veteran_app.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='veteranmember',
            name='next_of_kin_contact',
            field=models.CharField(blank=True, help_text='Next of kin contact number', max_length=15, validators=[veteran_app.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='veteranmember',
            name='spouse_contact',
            field=models.CharField(blank=True, help_text='Spouse contact number', max_length=15, null=True, validators=[veteran_app.validators.validate_phone_number]),
        ),
    ]
