# Generated by Django 4.2.9 on 2025-12-06 17:44

from django.db import migrations, models
import veteran_app.models
import veteran_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('veteran_app', '0024_add_phone_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselslide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='carousel/', validators=[veteran_app.validators.validate_image_extension, veteran_app.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='child',
            name='child_photo',
            field=models.ImageField(blank=True, help_text='Child photo (JPG, PNG, max 5MB)', null=True, upload_to='children/%Y/%m/', validators=[veteran_app.validators.validate_image_extension, veteran_app.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(help_text='Upload PDF, DOC, or image files (max 5MB)', upload_to='documents/%Y/%m/', validators=[veteran_app.validators.validate_file_extension, veteran_app.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='event',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='events/docs/%Y/%m/', validators=[veteran_app.validators.validate_file_extension, veteran_app.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='event',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/%Y/%m/', validators=[veteran_app.validators.validate_image_extension, veteran_app.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='bill_receipt',
            field=models.FileField(blank=True, null=True, upload_to='expenses/%Y/%m/', validators=[veteran_app.validators.validate_file_extension, veteran_app.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/', validators=[veteran_app.validators.validate_file_extension, veteran_app.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(help_text='Upload image (JPG, PNG, max 5MB)', upload_to='gallery/%Y/%m/', validators=[veteran_app.validators.validate_image_extension, veteran_app.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='jobportal',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload resume (PDF, DOC, DOCX, max 5MB)', null=True, upload_to='resumes/%Y/%m/', validators=[veteran_app.validators.validate_resume_extension, veteran_app.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='matrimonial',
            name='photo',
            field=models.ImageField(blank=True, help_text='Profile photo (JPG, PNG, max 5MB)', null=True, upload_to='matrimonial/%Y/%m/', validators=[veteran_app.validators.validate_image_extension, veteran_app.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'General_Info'), ('warning', 'Policy_Info'), ('success', 'Celebration_Info'), ('urgent', 'Obituary')], default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/', validators=[veteran_app.validators.validate_file_extension, veteran_app.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='userstate',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='State head profile photo (JPG, PNG, max 5MB)', null=True, upload_to='state_heads/%Y/', validators=[veteran_app.validators.validate_image_extension, veteran_app.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='veteranmember',
            name='document',
            field=models.FileField(blank=True, help_text='Subscription payment document (PDF, DOC, DOCX, JPG, PNG, max 5MB)', null=True, upload_to=veteran_app.models.get_upload_path, validators=[veteran_app.validators.validate_file_extension, veteran_app.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='veteranmember',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Upload profile photo (JPG, PNG, max 5MB)', null=True, upload_to='profiles/%Y/%m/', validators=[veteran_app.validators.validate_image_extension, veteran_app.validators.validate_file_size]),
        ),
    ]
