# Generated by Django 5.1.4 on 2025-12-26 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veteran_app', '0028_add_accounts_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association_number', models.CharField(db_index=True, max_length=30)),
                ('verified_by', models.CharField(blank=True, help_text='Organization or person who verified', max_length=200)),
                ('verification_date', models.DateTimeField(auto_now_add=True)),
                ('verification_method', models.CharField(choices=[('qr_scan', 'QR Code Scan'), ('manual', 'Manual Verification'), ('online', 'Online Verification')], default='manual', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Verification notes')),
            ],
            options={
                'verbose_name': 'Association Verification',
                'verbose_name_plural': 'Association Verifications',
                'ordering': ['-verification_date'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('codename', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='general', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('subscription', 'Subscription Payment'), ('donation', 'Donation'), ('expense', 'Expense'), ('refund', 'Refund'), ('other_income', 'Other Income'), ('event_fee', 'Event Fee'), ('crowdfunding', 'Crowd Funding')], max_length=20),
        ),
        migrations.AlterField(
            model_name='veteranmember',
            name='enrolled_date',
            field=models.DateField(help_text='Date when educational qualification/course was completed', verbose_name='Course Completed Date'),
        ),
        migrations.AlterField(
            model_name='veteranmember',
            name='nearest_dhq_text',
            field=models.CharField(help_text='Enter Nearest ECHS', max_length=200, verbose_name='Nearest ECHS'),
        ),
        migrations.AlterField(
            model_name='veteranmember',
            name='p_number',
            field=models.CharField(blank=True, help_text='Legacy field - use Association Number instead', max_length=50, null=True, verbose_name='Legacy Assn. Number (Deprecated)'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_system_role', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roles', to=settings.AUTH_USER_MODEL)),
                ('permissions', models.ManyToManyField(blank=True, to='veteran_app.permission')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoleAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create_role', 'Role Created'), ('update_role', 'Role Updated'), ('delete_role', 'Role Deleted'), ('assign_role', 'Role Assigned'), ('revoke_role', 'Role Revoked'), ('grant_permission', 'Permission Granted'), ('revoke_permission', 'Permission Revoked')], max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='veteran_app.permission')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='veteran_app.role')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rbac_actions_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rbac_actions_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='veteran_app.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('user', 'role')},
            },
        ),
    ]
